### ISSUE TITLE
packagenya tidak bekerja

### ISSUE THREAD

**Issue by novalbayusetiawan** [mul14/zenziva-sms#1]
step by step setelah instalasi via composer
apakah langsung di coba di controller?

saya masukkan sintaks ini di controler gak work

``` php
public function KirimSms(){
    $sms = new Sms('userzenziva', 'passzenziva');
    $sms->masking()->send('08215022166', 'Halo apa kabar?');
    return "Sukses";
}
```

sampai ke return sukses. tapi smsnya gak masuk, kredit di zenziva(SMS Masking) pun gak berkurang
apa ada yg kelupaan?

Terimakasih sebelumnya.

**Comment by mul14** [comment]
Coba dicek hasil dari website Zenziva. Caranya

``` php
$sms = new Sms('userzenziva', 'passzenziva');
$result = $sms->masking()->send('08215022166', 'Halo apa kabar?');

var_dump( $result->body );
```

**Comment by novalbayusetiawan** [comment]
`var_dump($result->body);`
hasilnya..

> string(144) " 5 Userkey / Passkey Salah "

user/pass salah?
tapi di coba login di zenziva.net->SMS Masking, bisa aja  gan

**Comment by mul14** [comment]
Apa username atau password mengandung non-alphanumeric? Misalnya karakter seperti `!?#$&` ?

**Comment by mul14** [comment]
Silahkan di-update dengan versi yang terbaru, lalu coba lagi.

**Comment by novalbayusetiawan** [comment]
Sudah saya update dengan versi yg baru gan..
tetap aja hasilnya seperti itu..

saya coba disini
[https://alpha.zenziva.net/apps/smsapi.php?userkey=xxx&passkey=xxx&nohp=xxx&pesan=xxx](url)

sukses aja gan

ada apa yaa??

**Comment by mul14** [comment]
Coba code-nya seperti ini

``` php
$sms = new Sms('userzenziva', 'passzenziva');

$sms->masking()
    ->subdomain('alpha')
    ->send('08215022166', 'Halo apa kabar?');

// Output: https://alpha.zenziva.net/apps/smsapi.php?userkey=userzenziva&passkey=passzenziva&tipe=masking&nohp=08215022166&pesan=Halo apa kabar?
```

**Comment by novalbayusetiawan** [comment]
Wow.. Sukses gan... Terimakasih Banyak..

Tapi kok pengirimnya "ZSMS" ya?

**Comment by mul14** [comment]
Ok sip. Thanks atas report-nya. Sepertinya harus update dokumentasi.

Btw, ZSMS itu memang dari Zenziva.
