### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by blegoh** [mul14/zenziva-sms#4]
Saya baru kemarin daftar zenziva yg sms center. bermasalah dengan domain nya. akhirnya saya ganti di folder vendor langsung, menggunakan http dan domain .co.id

**Comment by mul14** [comment]
Ngubah di bagian mananya mas @blegoh ? Mungkin bisa dibantu untuk resolve issue tersebut.

**Comment by blegoh** [comment]
ngubah domain doang sih, saya pull request aja ya https://github.com/mul14/zenziva-sms/pull/5

**Comment by mul14** [comment]
Halo @blegoh, sudah saya tambahkan fitur untuk ganti URL, silahkan dicoba. 

Berikut contoh penggunaannya:

```php
$sms->url('http://reguler.zenziva.co.id/apps/smsapi.php')
    ->send()

// Untuk melihat current URL
$sms->url();
```

**Comment by blegoh** [comment]
iya mas mul, thanks
